import type { LeadStatus } from "./state-machine";

/** Etiquetas legibles compartidas entre /admin y /profesional — un único sitio para no desincronizar el texto. */
export const LEAD_STATUS_LABEL: Record<LeadStatus, string> = {
  nuevo: "Nuevo",
  en_validacion: "En validación",
  validado: "Validado",
  en_cola: "En cola de asignación",
  sin_cobertura: "Sin cobertura",
  asignado: "Asignado",
  notificado: "Notificado al profesional",
  visto: "Visto por el profesional",
  aceptado: "Aceptado",
  contacto_pendiente: "Contacto pendiente",
  contacto_confirmado: "Contacto confirmado",
  presupuesto_pendiente: "Presupuesto pendiente",
  presupuesto_enviado: "Presupuesto enviado",
  en_revision_usuario: "En revisión del usuario",
  ganado: "Ganado",
  perdido: "Perdido",
  rechazado: "Rechazado",
  expirado: "Expirado",
  reasignacion_pendiente: "Reasignación pendiente",
  reasignado: "Reasignado",
  cancelado: "Cancelado",
  invalido: "Inválido",
  descartado: "Descartado",
  con_incidencia: "Con incidencia",
  enviado: "Enviado (heredado)",
  contactado: "Contactado (heredado)",
  cerrado: "Cerrado",
};

export type StatusTone = "good" | "warning" | "info" | "neutral";

export const LEAD_STATUS_TONE: Record<LeadStatus, StatusTone> = {
  nuevo: "info",
  en_validacion: "info",
  validado: "info",
  en_cola: "neutral",
  sin_cobertura: "neutral",
  asignado: "warning",
  notificado: "warning",
  visto: "warning",
  aceptado: "warning",
  contacto_pendiente: "warning",
  contacto_confirmado: "info",
  presupuesto_pendiente: "warning",
  presupuesto_enviado: "info",
  en_revision_usuario: "info",
  ganado: "good",
  perdido: "neutral",
  rechazado: "neutral",
  expirado: "neutral",
  reasignacion_pendiente: "warning",
  reasignado: "neutral",
  cancelado: "neutral",
  invalido: "neutral",
  descartado: "neutral",
  con_incidencia: "warning",
  enviado: "warning",
  contactado: "good",
  cerrado: "neutral",
};
